apiVersion: v2
name: debug-operator
description: Admission operator for injecting debugging profiles into Kubernetes workloads.
type: application
version: 1.2.0
appVersion: "1.2.0"
sources:
  - https://github.com/cfi2017/debug-operator
maintainers:
  - name: cfi2017
