{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "debug-operator.fullname" . }}
  labels:
    {{- include "debug-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: ["debug.hadron.re"]
    resources: ["debugprofiles"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["debug.hadron.re"]
    resources: ["debugprofiles/status"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "debug-operator.fullname" . }}
  labels:
    {{- include "debug-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "debug-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "debug-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
